### PR TITLE
FIX manager layout broken on MacOS

### PR DESCRIPTION
**Pull request by Charlie-XIAO**
See https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/pull/62#pullrequestreview-2112259557 and the following image. There is a margin around the body of the window, and also causes the main contents of the window to be mispositioned. This PR should fix both.

de65c6eb6405dedc3f6bbb94659d3f3

Pinging @ROMEEZHOU for a review to confirm that the problem is fixed on MacOS.

### CODE REVIEW

**Review by ROMEEZHOU — APPROVED** [review]
Works well on Mac! : )

**Comment by Charlie-XIAO** [comment]
@ROMEEZHOU Would you kindly share a screen shot here as well?

**Comment by ROMEEZHOU** [comment]
sure
Screenshot 2024-06-13 at 21 45 54

**Comment by Charlie-XIAO** [comment]
Thanks, looks good and merging

**Pull request merged**
