### PR TITLE
MAINT/RFC refactor maint scripts and add test workflow

### PR DESCRIPTION
**Pull request by Charlie-XIAO**
This finally adds the cross-platform testing workflow to our CI, though limited to the Rust test suite at the moment. Further work will include extending to the frontend test suite (`jest`) when there are frontend tests set up, and code coverage reports.

This PR also includes some refactoring of scripts. We now have the following:

- `npm run format [rs|js|all] [-- --fix]`: Format the codebase. One can specify a language (`all` by default). Add the `--fix` option to try to auto-fix formatting issues, otherwise it performs simple checks.
- `npm run lint [rs|js|all] [-- --fix]`: Lint the codebase, same arguments and options as above.
- `npm run test <rs|js> [testname] [-- --cov]`: Run the test suite (either `rs` or `js`, where `js` is not supported yet). Add an additional argument to specify a subset of tests to run (e.g., `npm run rs config` runs only `cargo test config` instead of `cargo test` the whole test suite). The `--cov` option in addition generates an HTML coverage report.

### CODE REVIEW

**Comment by rz2606** [comment]
I encountered some errors running the following commands on my machine:
b19fc36f65f8d10779d8d0303c7b1c5
npm run format failed the format check.

8ec1b5e522bb3ada4bcc825edca9d85
npm run format rs
The code check failed, there is a bug here.

I am trying to fix it. Could you help with that? Thanks!

**Comment by Charlie-XIAO** [comment]
This means that you've got formatting issues. Try fixing with  `npm run format -- --fix`

**Comment by Charlie-XIAO** [comment]
@CSCI-SHU-410-SE-Project/core-dev I reworked the maintenance tools around our project in this PR. You may check the top comment to see the usage.

**Review by Xinyu-Li-123 — APPROVED** [review]

**Review by ROMEEZHOU — APPROVED** [review]
LGTM

**Pull request merged**
