### PR TITLE
FIX bundler parsing error should not panic

### LINKED ISSUE #9: BUG Deskulpt can't handle syntax error in widget js code
When there is a syntax error in the widget js code, Deskulpt will crash. This happens at commit [442cf1](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/commit/442cf10d021eea29c86cc4b2905b53f8a28e4e3d), the head commit when I submit this issue. Below is a minimal example to reproduce this bug.

```javascript
const React = window.__DESKULPT__.defaultDeps.React;

// Syntax error here, misspell "const" as "conts", will crash Deskulpt
conts bannerText = "My Simple Banner";

function Banner() {
  return (
    <div>
      <h1>{bannerText}</h1>
    </div>
  );
}

export default {
  render: () => <Banner />,
};
```

And is the error message produced when Deskulpt crashes. It happens when I add this widget to the widgets folder and render. I run Deskulpt with  `npm run tauri dev`.
```
error: Expected ';', '}' or <eof>
 --> \\?\C:\Users\eiger\AppData\Roaming\com.tauri.deskulpt\widgets\ok-simple-banner\src\App.jsx:3:7
  |
3 | conts bannerText = "My Simple Banner";
  | ----- ^^^^^^^^^^
  | |
  | This is the expression part of an expression statement   

thread 'main' panicked at src\bundler.rs:171:21:
FATAL: Failed to parse module
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[0406/173441.713:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

@Charlie-XIAO @ROMEEZHOU You might want to check this out since we are writing tests for bundler this week

### PR DESCRIPTION
**Pull request by Charlie-XIAO**
Fixes #9.

This PR attempts to emit the parsing error in a formatted way instead of panicking (which is clearly wrong). The rendered error message of the reproducer in #9 should now look like this (no color, but formatted):

image

I've also added a corresponding widget to [`test-widgets`](https://github.com/CSCI-SHU-410-SE-Project/test-widgets/tree/main/err-bundler-parse).

/cc @Xinyu-Li-123 Can you give a review and confirm if this works?

### CODE REVIEW

**Comment by Xinyu-Li-123** [comment]
I have tested your changes locally. It works for other bugs, but Deskulpt still crashes if there are **duplicated `export default` statements**. Below is a minimal example to reproduce this crash

```tsx
const React = window.__DESKULPT__.defaultDeps.React;
const options = {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "numeric",
};


function Clock() {
  const [time, setTime] = React.useState(new Date().toLocaleString("en", options));

  function updateTime() {
    setTime(new Date().toLocaleTimeString("en", options));
  }
  setInterval(updateTime, 10000);

  return <h3>{time}</h3>;
}

const FOO = 1;
export default FOO;

export default {
  render: () => <Clock />,
};
```

The error message is as follows
```
thread 'main' panicked at C:\Users\Eiger\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_bundler-0.225.17\src\inline.rs:49:13:
internal error: entered unreachable code: Multiple identifiers equivalent up to span hygiene found: default#8        
First = default#5
Second = default#5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[0408/132929.720:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

**Comment by Charlie-XIAO** [comment]
This looks like an SWC error :(

**Comment by Xinyu-Li-123** [comment]
So should we merge this pr but open a new issue about this bug?

**Comment by Charlie-XIAO** [comment]
I opened https://github.com/swc-project/swc/issues/8824 upstream.

**Review by Xinyu-Li-123 — APPROVED** [review]
This PR fixes the bug that Deskulpt will crash once there is a syntax error in widget source code.

**Pull request merged**
