### PR TITLE
TST unit tests for `config.rs` and `testing` module for convenience

### PR DESCRIPTION
**Pull request by Charlie-XIAO**
This PR creates tests for `config.rs`, as described in the title.

It also creates the `testing.rs` module which currently contains the `assert_err_eq` utility to compare against an error against a `anyhow` error chain, which can be used by future unit tests as well.

### CODE REVIEW

**Review by ROMEEZHOU — COMMENTED** [review]
I encountered some errors running `cargo test` on my machine:
```
failures:

---- config::tests::test_read_conf_not_readable_error stdout ----
thread 'config::tests::test_read_conf_not_readable_error' panicked at src/testing.rs:42:17:
assertion failed: `(left == right)`

Diff < left / right > :
<IsADirectory
>PermissionDenied


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- config::tests::test_read_package_json_not_readable_error stdout ----
thread 'config::tests::test_read_package_json_not_readable_error' panicked at src/testing.rs:42:17:
assertion failed: `(left == right)`

Diff < left / right > :
<IsADirectory
>PermissionDenied




failures:
    config::tests::test_read_conf_not_readable_error
    config::tests::test_read_package_json_not_readable_error

test result: FAILED. 18 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--bin deskulpt`
```

Could you please take a look at this?

**Comment by rz2606** [comment]
> I encountered some errors running `cargo test` on my machine:
> 
> ```
> failures:
> 
> ---- config::tests::test_read_conf_not_readable_error stdout ----
> thread 'config::tests::test_read_conf_not_readable_error' panicked at src/testing.rs:42:17:
> assertion failed: `(left == right)`
> 
> Diff < left / right > :
> <IsADirectory
> >PermissionDenied
> 
> 
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> ---- config::tests::test_read_package_json_not_readable_error stdout ----
> thread 'config::tests::test_read_package_json_not_readable_error' panicked at src/testing.rs:42:17:
> assertion failed: `(left == right)`
> 
> Diff < left / right > :
> <IsADirectory
> >PermissionDenied
> 
> 
> 
> 
> failures:
>     config::tests::test_read_conf_not_readable_error
>     config::tests::test_read_package_json_not_readable_error
> 
> test result: FAILED. 18 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
> 
> error: test failed, to rerun pass `--bin deskulpt`
> ```
> 
> Could you please take a look at this?

  这个目录应该存的是deskulpt.conf.json文件并不是一个deskulpt.conf.json文件夹，这个问题已经解决了，现在跑单元测试已经正常了，测试验证已经通过了，符合预期期望
7d7bca9909e2816cdc3c0830681ba82

**Comment by Charlie-XIAO** [comment]
That's weird, seems that `read_to_string` will raise `PermissionDenied` for directories on Windows but this is not the case for other platforms. I skipped the error kind check and only checked that it is an IO error, which I think should be sufficient. Can you take another try @ROMEEZHOU?

**Comment by ROMEEZHOU** [comment]
Yes it works for me now 👍

**Comment by ROMEEZHOU** [comment]
And I will finish reviewing the code today :)

**Review by ROMEEZHOU — APPROVED** [review]
LGTM 👌

**Comment by rz2606** [comment]
> That's weird, seems that `read_to_string` will raise `PermissionDenied` for directories on Windows but this is not the case for other platforms. I skipped the error kind check and only checked that it is an IO error, which I think should be sufficient. Can you take another try @ROMEEZHOU?

I also ran your tests on my machine(windows) and found similar issues. This directory should contain a deskulpt.conf.json file, not a deskulpt.conf.json folder. This issue has been resolved, and now the unit tests are running normally. The test validation has passed, meeting the expected requirements.

7d7bca9909e2816cdc3c0830681ba82

327275a21992a84ed430a429ff83196

**Comment by Charlie-XIAO** [comment]
I think you are misunderstanding something here. That test case is to test whether we get the expected error, that is, failed to read the configuration file, and the configuration file is intentionally made into a folder to trigger the error.

**Comment by Charlie-XIAO** [comment]
We have talked about the test framework (how the `testing` module is set up and whether to replace `parameterize` with `rstest`) during the meeting, so I'm going to self-merge this one.

BTW I have also tested on Linux (WSL) and the tests are passing. This would be further validated in the test workflow PR.

**Comment by Charlie-XIAO** [comment]
We have talked about the test framework (how the `testing` module is set up and whether to replace `parameterize` with `rstest`) during the meeting, so I'm going to self-merge this one.

BTW I have also tested on Linux (WSL) and the tests are passing. This would be further validated in the test workflow PR.

**Pull request merged**
