### PR TITLE
API add `@deskulpt/sys` system information APIs

### PR DESCRIPTION
**Pull request by rz2606**
Adding sysInfo api and write a simple widget to display system info, need to resolve conflicting files.
TODO: real-time CPU usage info 

1fad7f2932fde1555c222323127c468

7c4bb7f57c8e048d03654b5d7a11413

90323cd777f551ae2c3ee43fcbba3de

### CODE REVIEW

**Comment by Xinyu-Li-123** [comment]
Please resolve the conflict with main branch first, so that I can preceed my review. You should 
- merge the commits on the remote main branch to your local feature branch. Below is the sequence of commands for merging
  ```bash
  # ensure you are on the main branch
  git checkout main
  # fetch changes on remote main branch and merge them to local main branch
  git pull origin main
  # go to local feature branch
  git checkout <local-feature-branch-name>
  # merge previous updates on local main branch to local feature branch
  git merge main
  ```
- resolve any merge conflict
- make thorough testing
- and push to the remote feature branch for review

Note that, in #49 , Charlie has migrated to tauri v2 and maken some changes to the organization of widget api. Please refer to that pr to modify your current organization of widget api source code accordingly.

**Comment by rz2606** [comment]
@Xinyu-Li-123 The conflict has been solved.

**Comment by Charlie-XIAO** [comment]
Some general comments in the first place:

- You misnamed `apis-sys` as `widget-sys`.
- You should place the Rust stuff under the existing `apis` folder instead of creating a new folder yourself.
- It seems that the `utils.rs` files is copied from `apis-fs` but you don't really need/use it.

**Comment by rz2606** [comment]
> Some general comments in the first place:
> 
> * You misnamed `apis-sys` as `widget-sys`.
> * You should place the Rust stuff under the existing `apis` folder instead of creating a new folder yourself.
> * It seems that the `utils.rs` files is copied from `apis-fs` but you don't really need/use it.

The issues above have been solved. A progress bar for average CPU usage is created instead of displaying 16 CPU separately.

image

**Review by Xinyu-Li-123 — APPROVED** [review]

**Comment by Xinyu-Li-123** [comment]
Please check again my changes on the branch. I have approved the PR. If there is no further problem, you could squash and merge this branch.

**Comment by Charlie-XIAO** [comment]
I'll take a look during today's meeting.

**Review by Charlie-XIAO — APPROVED** [review]
Thanks @rz2606 and @Xinyu-Li-123, this looks nice overall. I pushed some fixes, because there are some typos, unnecessary derivations, and incorrect typings. Except from these, there are some issues that remain:

- We should break down into finer granularity because `sysinfo` clearly allows us to do so.
- We are not providing good enough type hint, though I have improved a bit. We will need to export those types as well, which I have not yet considered in #29.

Merging on CI green because we are kinda in a rush. We will revisit this one in the future.

**Pull request merged**
